# Generated by Django 4.2.6 on 2023-10-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'اطلاعات اضافه'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='office',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دپارتمان'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='دسترسی'),
        ),
    ]
