# Generated by Django 4.2.6 on 2023-10-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_employee_options_remove_employee_office_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rank',
            field=models.CharField(blank=True, choices=[('warehouse', 'مدیریت انبار'), ('sale', 'مدیریت فروش'), ('production', 'مدیریت تولید'), ('finance', 'مدیریت مالی'), ('head', 'مدیر کارخانه')], max_length=100, null=True, verbose_name='دسترسی'),
        ),
    ]
