# Generated by Django 4.2.6 on 2023-10-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_employee_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='rank',
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('warehouse', 'مدیریت انبار'), ('sale', 'مدیریت فروش'), ('production', 'مدیریت تولید'), ('finance', 'مدیریت مالی'), ('head', 'مدیر کارخانه')], max_length=100, null=True, verbose_name='دپارتمان'),
        ),
    ]
