# Generated by Django 4.2.6 on 2023-10-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('مدیریت انبار', 'مدیریت انبار'), ('مدیریت فروش', 'مدیریت فروش'), ('مدیریت تولید', 'مدیریت تولید'), ('مدیریت مالی', 'مدیریت مالی'), ('مدیر کارخانه', 'مدیر کارخانه')], max_length=50, null=True, verbose_name='دپارتمان'),
        ),
    ]
